//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadados de Relação EDM

[assembly: EdmRelationshipAttribute("extjsformModel", "tree_extjs_ibfk_1", "tree_extjs", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ExtJSForm.Models.tree_extjs), "tree_extjs1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ExtJSForm.Models.tree_extjs), true)]

#endregion

namespace ExtJSForm.Models
{
    #region Contextos
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    public partial class extjsformEntities : ObjectContext
    {
        #region Construtores
    
        /// <summary>
        /// Inicializa um novo objeto extjsformEntities usando a cadeia de conexão localizada na seção 'extjsformEntities' do arquivo de configuração do aplicativo.
        /// </summary>
        public extjsformEntities() : base("name=extjsformEntities", "extjsformEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicialize um novo objeto extjsformEntities.
        /// </summary>
        public extjsformEntities(string connectionString) : base(connectionString, "extjsformEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicialize um novo objeto extjsformEntities.
        /// </summary>
        public extjsformEntities(EntityConnection connection) : base(connection, "extjsformEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos Parciais
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriedades de ObjectSet
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<infoextjsform> infoextjsform
        {
            get
            {
                if ((_infoextjsform == null))
                {
                    _infoextjsform = base.CreateObjectSet<infoextjsform>("infoextjsform");
                }
                return _infoextjsform;
            }
        }
        private ObjectSet<infoextjsform> _infoextjsform;
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<tree_extjs> tree_extjs
        {
            get
            {
                if ((_tree_extjs == null))
                {
                    _tree_extjs = base.CreateObjectSet<tree_extjs>("tree_extjs");
                }
                return _tree_extjs;
            }
        }
        private ObjectSet<tree_extjs> _tree_extjs;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet infoextjsform. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddToinfoextjsform(infoextjsform infoextjsform)
        {
            base.AddObject("infoextjsform", infoextjsform);
        }
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet tree_extjs. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddTotree_extjs(tree_extjs tree_extjs)
        {
            base.AddObject("tree_extjs", tree_extjs);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="extjsformModel", Name="infoextjsform")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class infoextjsform : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto infoextjsform.
        /// </summary>
        /// <param name="idInfoExtJS">Valor inicial da propriedade idInfoExtJS.</param>
        /// <param name="nome">Valor inicial da propriedade nome.</param>
        /// <param name="idade">Valor inicial da propriedade idade.</param>
        /// <param name="data">Valor inicial da propriedade data.</param>
        public static infoextjsform Createinfoextjsform(global::System.Int32 idInfoExtJS, global::System.String nome, global::System.Int32 idade, global::System.DateTime data)
        {
            infoextjsform infoextjsform = new infoextjsform();
            infoextjsform.idInfoExtJS = idInfoExtJS;
            infoextjsform.nome = nome;
            infoextjsform.idade = idade;
            infoextjsform.data = data;
            return infoextjsform;
        }

        #endregion

        #region Propriedades Simples
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idInfoExtJS
        {
            get
            {
                return _idInfoExtJS;
            }
            set
            {
                if (_idInfoExtJS != value)
                {
                    OnidInfoExtJSChanging(value);
                    ReportPropertyChanging("idInfoExtJS");
                    _idInfoExtJS = StructuralObject.SetValidValue(value, "idInfoExtJS");
                    ReportPropertyChanged("idInfoExtJS");
                    OnidInfoExtJSChanged();
                }
            }
        }
        private global::System.Int32 _idInfoExtJS;
        partial void OnidInfoExtJSChanging(global::System.Int32 value);
        partial void OnidInfoExtJSChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, false, "nome");
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idade
        {
            get
            {
                return _idade;
            }
            set
            {
                OnidadeChanging(value);
                ReportPropertyChanging("idade");
                _idade = StructuralObject.SetValidValue(value, "idade");
                ReportPropertyChanged("idade");
                OnidadeChanged();
            }
        }
        private global::System.Int32 _idade;
        partial void OnidadeChanging(global::System.Int32 value);
        partial void OnidadeChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime data
        {
            get
            {
                return _data;
            }
            set
            {
                OndataChanging(value);
                ReportPropertyChanging("data");
                _data = StructuralObject.SetValidValue(value, "data");
                ReportPropertyChanged("data");
                OndataChanged();
            }
        }
        private global::System.DateTime _data;
        partial void OndataChanging(global::System.DateTime value);
        partial void OndataChanged();

        #endregion

    }
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="extjsformModel", Name="tree_extjs")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tree_extjs : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto tree_extjs.
        /// </summary>
        /// <param name="id_tree">Valor inicial da propriedade id_tree.</param>
        /// <param name="nome">Valor inicial da propriedade nome.</param>
        public static tree_extjs Createtree_extjs(global::System.Int32 id_tree, global::System.String nome)
        {
            tree_extjs tree_extjs = new tree_extjs();
            tree_extjs.id_tree = id_tree;
            tree_extjs.nome = nome;
            return tree_extjs;
        }

        #endregion

        #region Propriedades Simples
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_tree
        {
            get
            {
                return _id_tree;
            }
            set
            {
                if (_id_tree != value)
                {
                    Onid_treeChanging(value);
                    ReportPropertyChanging("id_tree");
                    _id_tree = StructuralObject.SetValidValue(value, "id_tree");
                    ReportPropertyChanged("id_tree");
                    Onid_treeChanged();
                }
            }
        }
        private global::System.Int32 _id_tree;
        partial void Onid_treeChanging(global::System.Int32 value);
        partial void Onid_treeChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, false, "nome");
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> parent_id
        {
            get
            {
                return _parent_id;
            }
            set
            {
                Onparent_idChanging(value);
                ReportPropertyChanging("parent_id");
                _parent_id = StructuralObject.SetValidValue(value, "parent_id");
                ReportPropertyChanged("parent_id");
                Onparent_idChanged();
            }
        }
        private Nullable<global::System.Int32> _parent_id;
        partial void Onparent_idChanging(Nullable<global::System.Int32> value);
        partial void Onparent_idChanged();

        #endregion

        #region Propriedades de Navegação
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("extjsformModel", "tree_extjs_ibfk_1", "tree_extjs1")]
        public EntityCollection<tree_extjs> tree_extjs1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tree_extjs>("extjsformModel.tree_extjs_ibfk_1", "tree_extjs1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tree_extjs>("extjsformModel.tree_extjs_ibfk_1", "tree_extjs1", value);
                }
            }
        }
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("extjsformModel", "tree_extjs_ibfk_1", "tree_extjs")]
        public tree_extjs tree_extjs2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tree_extjs>("extjsformModel.tree_extjs_ibfk_1", "tree_extjs").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tree_extjs>("extjsformModel.tree_extjs_ibfk_1", "tree_extjs").Value = value;
            }
        }
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tree_extjs> tree_extjs2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tree_extjs>("extjsformModel.tree_extjs_ibfk_1", "tree_extjs");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tree_extjs>("extjsformModel.tree_extjs_ibfk_1", "tree_extjs", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
