//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ExtJSForm.Models
{
    #region Contextos
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    public partial class extjsformEntities : ObjectContext
    {
        #region Construtores
    
        /// <summary>
        /// Inicializa um novo objeto extjsformEntities usando a cadeia de conexão localizada na seção 'extjsformEntities' do arquivo de configuração do aplicativo.
        /// </summary>
        public extjsformEntities() : base("name=extjsformEntities", "extjsformEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicialize um novo objeto extjsformEntities.
        /// </summary>
        public extjsformEntities(string connectionString) : base(connectionString, "extjsformEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicialize um novo objeto extjsformEntities.
        /// </summary>
        public extjsformEntities(EntityConnection connection) : base(connection, "extjsformEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos Parciais
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriedades de ObjectSet
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<infoextjsform> infoextjsform
        {
            get
            {
                if ((_infoextjsform == null))
                {
                    _infoextjsform = base.CreateObjectSet<infoextjsform>("infoextjsform");
                }
                return _infoextjsform;
            }
        }
        private ObjectSet<infoextjsform> _infoextjsform;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet infoextjsform. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddToinfoextjsform(infoextjsform infoextjsform)
        {
            base.AddObject("infoextjsform", infoextjsform);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="extjsformModel", Name="infoextjsform")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class infoextjsform : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto infoextjsform.
        /// </summary>
        /// <param name="idInfoExtJS">Valor inicial da propriedade idInfoExtJS.</param>
        /// <param name="nome">Valor inicial da propriedade nome.</param>
        /// <param name="idade">Valor inicial da propriedade idade.</param>
        /// <param name="data">Valor inicial da propriedade data.</param>
        public static infoextjsform Createinfoextjsform(global::System.Int32 idInfoExtJS, global::System.String nome, global::System.Int32 idade, global::System.DateTime data)
        {
            infoextjsform infoextjsform = new infoextjsform();
            infoextjsform.idInfoExtJS = idInfoExtJS;
            infoextjsform.nome = nome;
            infoextjsform.idade = idade;
            infoextjsform.data = data;
            return infoextjsform;
        }

        #endregion

        #region Propriedades Simples
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idInfoExtJS
        {
            get
            {
                return _idInfoExtJS;
            }
            set
            {
                if (_idInfoExtJS != value)
                {
                    OnidInfoExtJSChanging(value);
                    ReportPropertyChanging("idInfoExtJS");
                    _idInfoExtJS = StructuralObject.SetValidValue(value, "idInfoExtJS");
                    ReportPropertyChanged("idInfoExtJS");
                    OnidInfoExtJSChanged();
                }
            }
        }
        private global::System.Int32 _idInfoExtJS;
        partial void OnidInfoExtJSChanging(global::System.Int32 value);
        partial void OnidInfoExtJSChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, false, "nome");
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idade
        {
            get
            {
                return _idade;
            }
            set
            {
                OnidadeChanging(value);
                ReportPropertyChanging("idade");
                _idade = StructuralObject.SetValidValue(value, "idade");
                ReportPropertyChanged("idade");
                OnidadeChanged();
            }
        }
        private global::System.Int32 _idade;
        partial void OnidadeChanging(global::System.Int32 value);
        partial void OnidadeChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime data
        {
            get
            {
                return _data;
            }
            set
            {
                OndataChanging(value);
                ReportPropertyChanging("data");
                _data = StructuralObject.SetValidValue(value, "data");
                ReportPropertyChanged("data");
                OndataChanged();
            }
        }
        private global::System.DateTime _data;
        partial void OndataChanging(global::System.DateTime value);
        partial void OndataChanged();

        #endregion

    }

    #endregion

}
